name: PR Reviewer

# controls when the action will run
on:
  pull_request:
    types: [opened, synchronize]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # this is required to fetch all history

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Execute script
        run: python .github/actions_scripts/pr_reviewer.py
